#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfconf
Version  : 4.12.1
Release  : 12
URL      : http://archive.xfce.org/src/xfce/xfconf/4.12/xfconf-4.12.1.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfconf/4.12/xfconf-4.12.1.tar.bz2
Summary  : Configuration library for Xfce
Group    : Development/Tools
License  : GPL-2.0
Requires: xfconf-bin
Requires: xfconf-lib
Requires: xfconf-data
Requires: xfconf-doc
Requires: xfconf-locales
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libxfce4util-1.0)

%description


%package bin
Summary: bin components for the xfconf package.
Group: Binaries
Requires: xfconf-data

%description bin
bin components for the xfconf package.


%package data
Summary: data components for the xfconf package.
Group: Data

%description data
data components for the xfconf package.


%package dev
Summary: dev components for the xfconf package.
Group: Development
Requires: xfconf-lib
Requires: xfconf-bin
Requires: xfconf-data
Provides: xfconf-devel

%description dev
dev components for the xfconf package.


%package doc
Summary: doc components for the xfconf package.
Group: Documentation

%description doc
doc components for the xfconf package.


%package lib
Summary: lib components for the xfconf package.
Group: Libraries
Requires: xfconf-data

%description lib
lib components for the xfconf package.


%package locales
Summary: locales components for the xfconf package.
Group: Default

%description locales
locales components for the xfconf package.


%prep
%setup -q -n xfconf-4.12.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
%find_lang xfconf

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/xfconf/xfconfd

%files bin
%defattr(-,root,root,-)
/usr/bin/xfconf-query

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.xfce.Xfconf.service

%files dev
%defattr(-,root,root,-)
/usr/include/xfce4/xfconf-0/xfconf/xfconf-binding.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf-channel.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf-errors.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf-types.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/xfconf/ch01.html
/usr/share/gtk-doc/html/xfconf/ch02.html
/usr/share/gtk-doc/html/xfconf/ch03.html
/usr/share/gtk-doc/html/xfconf/home.png
/usr/share/gtk-doc/html/xfconf/index.html
/usr/share/gtk-doc/html/xfconf/left-insensitive.png
/usr/share/gtk-doc/html/xfconf/left.png
/usr/share/gtk-doc/html/xfconf/right-insensitive.png
/usr/share/gtk-doc/html/xfconf/right.png
/usr/share/gtk-doc/html/xfconf/style.css
/usr/share/gtk-doc/html/xfconf/up-insensitive.png
/usr/share/gtk-doc/html/xfconf/up.png
/usr/share/gtk-doc/html/xfconf/xfconf-xfconf-backend.html
/usr/share/gtk-doc/html/xfconf/xfconf-xfconf-binding.html
/usr/share/gtk-doc/html/xfconf/xfconf-xfconf-channel.html
/usr/share/gtk-doc/html/xfconf/xfconf-xfconf-errors.html
/usr/share/gtk-doc/html/xfconf/xfconf-xfconf-types.html
/usr/share/gtk-doc/html/xfconf/xfconf-xfconf.html
/usr/share/gtk-doc/html/xfconf/xfconf.devhelp2

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f xfconf.lang 
%defattr(-,root,root,-)

