#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
Name     : xfconf
Version  : 4.20.0
Release  : 37
URL      : https://archive.xfce.org/src/xfce/xfconf/4.20/xfconf-4.20.0.tar.bz2
Source0  : https://archive.xfce.org/src/xfce/xfconf/4.20/xfconf-4.20.0.tar.bz2
Summary  : Configuration library for Xfce
Group    : Development/Tools
License  : GPL-2.0
Requires: xfconf-bin = %{version}-%{release}
Requires: xfconf-data = %{version}-%{release}
Requires: xfconf-lib = %{version}-%{release}
Requires: xfconf-license = %{version}-%{release}
Requires: xfconf-locales = %{version}-%{release}
Requires: xfconf-services = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : docbook-xml
BuildRequires : file
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : sed
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/xfce/xfconf/-/blob/master/COPYING)

%package bin
Summary: bin components for the xfconf package.
Group: Binaries
Requires: xfconf-data = %{version}-%{release}
Requires: xfconf-license = %{version}-%{release}
Requires: xfconf-services = %{version}-%{release}

%description bin
bin components for the xfconf package.


%package data
Summary: data components for the xfconf package.
Group: Data

%description data
data components for the xfconf package.


%package dev
Summary: dev components for the xfconf package.
Group: Development
Requires: xfconf-lib = %{version}-%{release}
Requires: xfconf-bin = %{version}-%{release}
Requires: xfconf-data = %{version}-%{release}
Provides: xfconf-devel = %{version}-%{release}
Requires: xfconf = %{version}-%{release}

%description dev
dev components for the xfconf package.


%package doc
Summary: doc components for the xfconf package.
Group: Documentation

%description doc
doc components for the xfconf package.


%package lib
Summary: lib components for the xfconf package.
Group: Libraries
Requires: xfconf-data = %{version}-%{release}
Requires: xfconf-license = %{version}-%{release}

%description lib
lib components for the xfconf package.


%package license
Summary: license components for the xfconf package.
Group: Default

%description license
license components for the xfconf package.


%package locales
Summary: locales components for the xfconf package.
Group: Default

%description locales
locales components for the xfconf package.


%package services
Summary: services components for the xfconf package.
Group: Systemd services
Requires: systemd

%description services
services components for the xfconf package.


%prep
%setup -q -n xfconf-4.20.0
cd %{_builddir}/xfconf-4.20.0
pushd ..
cp -a xfconf-4.20.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735687527
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735687527
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfconf
cp %{_builddir}/xfconf-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xfconf/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang xfconf
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/xfce4/xfconf/xfconfd
/usr/lib64/xfce4/xfconf/xfconfd

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xfconf-query
/usr/bin/xfconf-query

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Xfconf-0.typelib
/usr/share/bash-completion/completions/xfconf-query
/usr/share/dbus-1/services/org.xfce.Xfconf.service
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/xfce4/xfconf-0/xfconf/xfconf-binding.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf-channel.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf-errors.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf-types.h
/usr/include/xfce4/xfconf-0/xfconf/xfconf.h
/usr/lib64/libxfconf-0.so
/usr/lib64/pkgconfig/libxfconf-0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/xfconf/annotation-glossary.html
/usr/share/gtk-doc/html/xfconf/ch01.html
/usr/share/gtk-doc/html/xfconf/ch02.html
/usr/share/gtk-doc/html/xfconf/ch03.html
/usr/share/gtk-doc/html/xfconf/ch04.html
/usr/share/gtk-doc/html/xfconf/home.png
/usr/share/gtk-doc/html/xfconf/index.html
/usr/share/gtk-doc/html/xfconf/left-insensitive.png
/usr/share/gtk-doc/html/xfconf/left.png
/usr/share/gtk-doc/html/xfconf/right-insensitive.png
/usr/share/gtk-doc/html/xfconf/right.png
/usr/share/gtk-doc/html/xfconf/style.css
/usr/share/gtk-doc/html/xfconf/up-insensitive.png
/usr/share/gtk-doc/html/xfconf/up.png
/usr/share/gtk-doc/html/xfconf/xfconf-Error-Reporting.html
/usr/share/gtk-doc/html/xfconf/xfconf-Xfconf-Backend.html
/usr/share/gtk-doc/html/xfconf/xfconf-Xfconf-Channel.html
/usr/share/gtk-doc/html/xfconf/xfconf-Xfconf-GObject-Binding.html
/usr/share/gtk-doc/html/xfconf/xfconf-Xfconf-Library-Core.html
/usr/share/gtk-doc/html/xfconf/xfconf-Xfconf-Types.html
/usr/share/gtk-doc/html/xfconf/xfconf.devhelp2

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/gio/modules/libxfconfgsettingsbackend.so
/V3/usr/lib64/libxfconf-0.so.3.0.0
/usr/lib64/gio/modules/libxfconfgsettingsbackend.so
/usr/lib64/libxfconf-0.so.3
/usr/lib64/libxfconf-0.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfconf/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/xfconfd.service

%files locales -f xfconf.lang
%defattr(-,root,root,-)

